source 'https://rubygems.org'

# Specify your gem's dependencies in eBlockerDNS.gemspec
gemspec

gem 'async-io', :path => '../../../third_party/async-io'

gem 'process-daemon', :path => '../../../third_party/process-daemon'
#gem 'process-daemon' # on macOS

gem 'hsluv'

gem 'nio4r', '~>1.2.1'
