<?xml version='1.0' encoding='utf-8'?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <parent>
        <artifactId>eblocker-parent</artifactId>
        <groupId>org.eblocker</groupId>
        <version>4.0.3</version>
        <relativePath>../../build/parent/pom.xml</relativePath>
    </parent>
    <modelVersion>4.0.0</modelVersion>
    <name>eBlocker - Certificate Validator for Squid</name>
    <groupId>org.eblocker</groupId>
    <artifactId>eblocker-certificate-validator</artifactId>
    <dependencies>
        <dependency>
            <groupId>org.eblocker</groupId>
            <artifactId>eblocker-crypto</artifactId>
        </dependency>
        <dependency>
            <groupId>com.google.guava</groupId>
            <artifactId>guava</artifactId>
        </dependency>
        <dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>slf4j-api</artifactId>
        </dependency>
        <dependency>
            <groupId>org.apache.logging.log4j</groupId>
            <artifactId>log4j-slf4j2-impl</artifactId>
        </dependency>
        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.mockito</groupId>
            <artifactId>mockito-core</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.eblocker</groupId>
            <artifactId>eblocker-icapserver</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.mock-server</groupId>
            <artifactId>mockserver-netty</artifactId>
            <exclusions>
                <exclusion>
                    <artifactId>logback-classic</artifactId>
                    <groupId>ch.qos.logback</groupId>
                </exclusion>
            </exclusions>
            <scope>test</scope>
        </dependency>
    </dependencies>
    <build>
        <finalName>${project.artifactId}_${project.version}.${maven.build.timestamp}_all</finalName>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-jar-plugin</artifactId>
                <configuration>
                    <archive>
                        <manifest>
                            <addClasspath>true</addClasspath>
                            <addDefaultImplementationEntries>true</addDefaultImplementationEntries>
                            <mainClass>org.eblocker.certificate.validator.squid.CertificateValidatorApp</mainClass>
                            <useUniqueVersions>false</useUniqueVersions>
                        </manifest>
                    </archive>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-dependency-plugin</artifactId>
                <executions>
                    <execution>
                        <id>copy-dependencies</id>
                        <phase>package</phase>
                        <goals>
                            <goal>copy-dependencies</goal>
                        </goals>
                        <configuration>
                            <outputDirectory>${project.build.directory}/lib</outputDirectory>
                            <overWriteReleases>false</overWriteReleases>
                            <overWriteSnapshots>false</overWriteSnapshots>
                            <overWriteIfNewer>true</overWriteIfNewer>
                            <includeScope>runtime</includeScope>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-resources-plugin</artifactId>
                <executions>
                    <execution>
                        <id>copy-resources-bin</id>
                        <phase>package</phase>
                        <goals>
                            <goal>copy-resources</goal>
                        </goals>
                        <configuration>
                            <outputDirectory>${project.build.directory}/package/bin</outputDirectory>
                            <resources>
                                <resource>
                                    <directory>src/main/package/bin</directory>
                                    <filtering>true</filtering>
                                </resource>
                            </resources>
                        </configuration>
                    </execution>
                    <execution>
                        <id>copy-resources-systemd</id>
                        <phase>package</phase>
                        <goals>
                            <goal>copy-resources</goal>
                        </goals>
                        <configuration>
                            <outputDirectory>${project.build.directory}/package/systemd</outputDirectory>
                            <resources>
                                <resource>
                                    <directory>src/main/package/systemd</directory>
                                    <filtering>false</filtering>
                                </resource>
                            </resources>
                        </configuration>
                    </execution>
                    <execution>
                        <id>copy-configuration</id>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <artifactId>jdeb</artifactId>
                <groupId>org.vafer</groupId>
                <executions>
                    <execution>
                        <phase>package</phase>
                        <goals>
                            <goal>jdeb</goal>
                        </goals>
                        <configuration>
                            <deb>${debTargetDir}/${project.artifactId}_${project.version}.${maven.build.timestamp}_all.deb</deb>
                            <snapshotExpand>true</snapshotExpand>
                            <dataSet>
                                <data>
                                    <src>${project.build.directory}/${project.build.finalName}.jar</src>
                                    <type>file</type>
                                    <mapper>
                                        <type>perm</type>
                                        <prefix>/opt/eblocker-network/certificate-validator/lib</prefix>
                                    </mapper>
                                </data>
                                <data>
                                    <src>${project.build.directory}/lib/</src>
                                    <type>directory</type>
                                    <mapper>
                                        <type>perm</type>
                                        <prefix>/opt/eblocker-network/certificate-validator/lib</prefix>
                                    </mapper>
                                </data>
                                <data>
                                    <src>${project.build.directory}/package/bin/</src>
                                    <type>directory</type>
                                    <mapper>
                                        <type>perm</type>
                                        <prefix>/opt/eblocker-network/certificate-validator/bin</prefix>
                                        <filemode>755</filemode>
                                    </mapper>
                                </data>
                                <data>
                                    <src>${project.build.directory}/package/systemd</src>
                                    <type>directory</type>
                                    <mapper>
                                        <type>perm</type>
                                        <prefix>/lib/systemd/system</prefix>
                                        <filemode>644</filemode>
                                    </mapper>
                                </data>
                                <data>
                                    <type>template</type>
                                    <mapper>
                                        <type>perm</type>
                                        <user>certvalidatord</user>
                                        <group>certvalidatord</group>
                                        <dirmode>750</dirmode>
                                    </mapper>
                                    <paths>
                                        <path>/var/log/certvalidator</path>
                                    </paths>
                                </data>
                                <data>
                                    <type>template</type>
                                    <mapper>
                                        <type>perm</type>
                                        <user>certvalidatord</user>
                                        <group>certvalidatord</group>
                                        <dirmode>750</dirmode>
                                    </mapper>
                                    <paths>
                                        <path>/var/cache/certvalidator</path>
                                    </paths>
                                </data>
                            </dataSet>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>org.codehaus.mojo</groupId>
                <artifactId>exec-maven-plugin</artifactId>
                <configuration>
                    <executable>java</executable>
                    <arguments>
                        <argument>-classpath</argument>
                        <classpath />
                        <argument>org.eblocker.certificate.validator.squid.CertificateValidatorApp</argument>
                    </arguments>
                </configuration>
            </plugin>
        </plugins>
    </build>
</project>
