DNS_HOME := $(DESTDIR)/opt/eblocker-coredns

# Remove debug information and absolute build paths:
GO_BUILD_FLAGS := -trimpath -ldflags="-s -w"

ifeq ($(ARCH),armhf)
    GOARCH := arm
else
    GOARCH := $(ARCH)
endif

all: eblocker-coredns

test:
	go test ./...

clean:
	rm -f eblocker-coredns Corefile hosts

eblocker-coredns: eblocker-coredns.go configupdater.go domainfilter/setup.go domainfilter/domainfilter.go resolverstats/setup.go resolverstats/resolverstats.go
	GOARCH=$(GOARCH) CGO_ENABLED=0 go build $(GO_BUILD_FLAGS)

install: eblocker-coredns
	mkdir -p $(DNS_HOME) $(DNS_HOME)/bin
	cp eblocker-coredns $(DNS_HOME)/bin

package:
	dpkg-buildpackage -us -uc -b --host-arch=$(ARCH)
